services:
  web:
    build: .
    environment:
      - PORT=8080
      - SECRET_KEY=${SECRET_KEY:-change_me_in_production}
      - FLASK_ENV=production
    ports:
      - "8080:8080"
    restart: unless-stopped