version: '3'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - SECRET_KEY=change_me_in_production
      - FLASK_ENV=production
    volumes:
      - ./votes.db:/app/votes.db
    restart: unless-stopped